In [11]:
!pip install easyocr jiwer pandas tqdm matplotlib seaborn

Requirement already satisfied: easyocr in /usr/local/lib/python3.12/dist-packages (1.7.2)
Requirement already satisfied: jiwer in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.3.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from easyocr) (2.10.0+cu128)
Requirement already satisfied: torchvision>=0.5 in /usr/local/lib/python3.12/dist-packages (from easyocr) (0.25.0+cu128)
Requirement already satisfied: opencv-python-headless in /usr/local/lib/python3.12/dist-packages (from easyocr) (4.13.0.92)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from easyocr) (1.16.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from easyocr) (2.4.6)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from easyocr) (11.3.0)
Requirement already satisfied: scikit-image in /usr/local/lib/python3.12/dist-packages (from easyocr) (0.25.2)
Requirement already satisfied: python-bidi in /usr/local/lib/python3.12/dist-packages (from easyocr) (0.6.10)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from easyocr) (6.0.3)
Requirement already satisfied: Shapely in /usr/local/lib/python3.12/dist-packages (from easyocr) (2.1.2)
Requirement already satisfied: pyclipper in /usr/local/lib/python3.12/dist-packages (from easyocr) (1.4.0)
Requirement already satisfied: ninja in /usr/local/lib/python3.12/dist-packages (from easyocr) (1.13.0)
Requirement already satisfied: click>=8.1.8 in /usr/local/lib/python3.12/dist-packages (from jiwer) (8.3.2)
Requirement already satisfied: rapidfuzz>=3.9.7 in /usr/local/lib/python3.12/dist-packages (from jiwer) (3.14.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch->easyocr) (1.5.4)
Requirement already satisfied: imageio!=2.35.0,>=2.33 in /usr/local/lib/python3.12/dist-packages (from scikit-image->easyocr) (2.37.3)
Requirement already satisfied: tifffile>=2022.8.12 in /usr/local/lib/python3.12/dist-packages (from scikit-image->easyocr) (2026.3.3)
Requirement already satisfied: lazy-loader>=0.4 in /usr/local/lib/python3.12/dist-packages (from scikit-image->easyocr) (0.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->easyocr) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->easyocr) (3.0.3)

In [12]:
import os
from pathlib import Path
import pandas as pd
import numpy as np
from tqdm import tqdm
import matplotlib.pyplot as plt
import seaborn as sns
import easyocr
from jiwer import wer

In [13]:
ROOT = Path("/kaggle/input/datasets/evgeniyashpirnova/trainvaldataset/all_data")

# Загружаем только validation
val_df = pd.read_csv(ROOT / "val" / "labels.csv")

val_df["image_path"] = val_df["filename"].apply(
    lambda x: str(ROOT / "val" / x)
)

dataset = val_df

## Расчет расстояния Левенштейна и метрики CER

### Расстояние Левенштейна

Расстояние Левенштейна характеризуется минимальным количеством операций, нужным, чтобы превратить одну строку в другую.

**Формула:**

$$
LD = S + D + I
$$

где:
S (Substitutions)— количество замен символов;

D (Deletions) — количество удалений символов;

I (Insertions) — количество вставленных лишних символов.

### Метрика CER

CER показывает, какую долю символов OCR распознал неправильно.

**Формула:**

$$
CER = \frac{LD}{N}
$$

где:
N— количество символов в эталонной строке (*Ground Truth*).

Чем меньше значение CER, тем лучше качество распознавания.

### Метрика WER

WER показывает долю слов, распознанных системой OCR неверно.

Для вычисления WER используется расстояние Левенштейна на уровне слов, а не отдельных символов.

Формула та же, что и в CER.

In [14]:
def levenshtein_distance(s1, s2):
    m, n = len(s1), len(s2)

    dp = [[0]*(n+1) for _ in range(m+1)]

    for i in range(m+1):
        dp[i][0] = i

    for j in range(n+1):
        dp[0][j] = j

    for i in range(1, m+1):
        for j in range(1, n+1):

            cost = 0 if s1[i-1] == s2[j-1] else 1

            dp[i][j] = min(
                dp[i-1][j] + 1,
                dp[i][j-1] + 1,
                dp[i-1][j-1] + cost
            )

    return dp[m][n]


def cer(gt, pred):
    if len(gt) == 0:
        return 0 if len(pred) == 0 else 1

    return levenshtein_distance(gt, pred) / len(gt)

### Объявление модели распознавания текста

In [15]:
reader = easyocr.Reader(
    ['de'],
    gpu=True,
    recog_network="best_accuracy",
    user_network_directory='custom_EasyOCR/model',
    model_storage_directory='custom_EasyOCR/user_network',
)

In [16]:
def recognize_text(image_path):
    result = reader.readtext(
        str(image_path),
        detail=0,
        paragraph=True
    )

    text = " ".join(result)

    return text.strip()

In [19]:
df = pd.read_csv("/kaggle/input/datasets/evgeniyashpirnova/trainvaldataset/all_data/val/labels.csv")

print(df.columns.tolist())
df.head()

['filename', 'words']

          filename           words
0  crop_000282.jpg  oxfordtube com
1  crop_002014.jpg   Franziusallee
2  crop_001719.jpg       Stolzeweg
3  crop_000994.jpg       traumhaft
4  crop_002033.jpg      Fahrschule

## Распознавание текста и сравнение с эталонным: оценка по метрикам cer, wer, accuracy (полное совпадение)

In [20]:
def evaluate_dataset(dataset):
    results = []

    for _, row in tqdm(dataset.iterrows(), total=len(dataset)):
        gt_text = str(row["words"])

        pred_text = recognize_text(row["image_path"])

        results.append({
            "filename": row["filename"],
            "gt": gt_text,
            "pred": pred_text,
            "cer": cer(gt_text, pred_text),
            "wer": wer(gt_text, pred_text),
            "exact_match": int(
                gt_text.strip() == pred_text.strip()
            )
        })

    return pd.DataFrame(results)

## Вывод метрик
В среднем около 31 символа из 100 распознаются неверно.

Чуть больше половины слов распознаются с ошибкой.

Только 57% изображений распознаны абсолютно без ошибок.

In [22]:
def calculate_metrics(df):
    return {
        "CER": df["cer"].mean(),
        "WER": df["wer"].mean(),
        "Accuracy": df["exact_match"].mean()
    }

val_metrics = calculate_metrics(val_results)

pd.DataFrame([val_metrics])

        CER       WER  Accuracy
0  0.310293  0.552726  0.570093

## Слова, которые были распознаны неправильно

In [25]:
errors = val_results[
    val_results["exact_match"] == 0
]

for _, row in errors.head(10).iterrows():
    print("FILE:")
    print(row["filename"])

    print("\nGT:")
    print(row["gt"])

    print("\nPRED:")
    print(row["pred"])

    print("\nCER:", round(row["cer"], 4))
    print("\nWER:", round(row["wer"], 4))

FILE:
crop_001719.jpg

GT:
Stolzeweg

PRED:
Stolzeweg_

CER: 0.1111

WER: 1.0
FILE:
crop_000994.jpg

GT:
traumhaft

PRED:
ge traumhaft

CER: 0.3333

WER: 1.0
FILE:
crop_002033.jpg

GT:
Fahrschule

PRED:
Fakrschule

CER: 0.1

WER: 1.0
FILE:
crop_000297.jpg

GT:
GEORGE

PRED:
GEORGE '

CER: 0.3333

WER: 1.0
FILE:
crop_001590.jpg

GT:
Zuwiderhandlumngen

PRED:
Jos Zuwiderhandluingenz

CER: 0.3333

WER: 2.0
FILE:
crop_000290.jpg

GT:
PLACE

PRED:
PUACE

CER: 0.2

WER: 1.0
FILE:
crop_001727.jpg

GT:
PIZZA

PRED:
PIZA

CER: 0.2

WER: 1.0
FILE:
crop_000507.jpg

GT:
Bücher

PRED:
Bucher

CER: 0.1667

WER: 1.0
FILE:
crop_001795.jpg

GT:
&

PRED:


CER: 1.0

WER: 1.0
FILE:
crop_000196.jpg

GT:
Comfort

PRED:
Comlort

CER: 0.1429

WER: 1.0